const actionTypes = {
  SET_SAVINGS_AMOUNT: 'SET_SAVINGS_AMOUNT',
  SET_INTEREST_RATE: 'SET_INTEREST_RATE',
  SET_MONTHLY_SAVE_AMOUNT: 'SET_MONTHLY_SAVE_AMOUNT',
  CALCULATE_AMOUNT_SUCCESS: 'CALCULATE_AMOUNT_SUCCESS',
  CALCULATE_AMOUNT_FAILURE: 'CALCULATE_AMOUNT_FAILURE',
}

export default actionTypes;
